//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rubicon.SecurityManager.Clients.Web.UI.AccessControl {
    
    public partial class EditAccessControlEntryControl {
        protected Rubicon.Data.DomainObjects.ObjectBinding.Web.DomainObjectDataSourceControl CurrentObject;
        protected Rubicon.Web.UI.Controls.FormGridManager FormGridManager;
        protected System.Web.UI.HtmlControls.HtmlTable FormGrid;
        protected Rubicon.ObjectBinding.Web.UI.Controls.BocReferenceValue SpecificAbstractRoleField;
        protected Rubicon.ObjectBinding.Web.UI.Controls.BocReferenceValue SpecificPositionField;
        protected Rubicon.ObjectBinding.Web.UI.Controls.BocTextValue PriorityField;
        protected Rubicon.ObjectBinding.Web.UI.Controls.BocTextValue ActualPriority;
        protected Rubicon.Web.UI.Controls.FormGridLabel PermissionsLabel;
        protected System.Web.UI.WebControls.PlaceHolder PermissionsPlaceHolder;
    }
}
