//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rubicon.SecurityManager.Clients.Web.UI.AccessControl {
    
    public partial class EditPermissionControl {
        protected Rubicon.Data.DomainObjects.ObjectBinding.Web.DomainObjectDataSourceControl CurrentObject;
        protected Rubicon.ObjectBinding.Web.UI.Controls.BusinessObjectReferenceDataSourceControl AccessType;
        protected Rubicon.ObjectBinding.Web.UI.Controls.BocTextValue NameField;
        protected Rubicon.ObjectBinding.Web.UI.Controls.BocBooleanValue AllowedField;
    }
}
