//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rubicon.SecurityManager.Clients.Web.UI.AccessControl {
    
    public partial class EditAccessControlListControl {
        protected Rubicon.Data.DomainObjects.ObjectBinding.Web.DomainObjectDataSourceControl CurrentObject;
        protected System.Web.UI.HtmlControls.HtmlGenericControl StateCombinationControls;
        protected System.Web.UI.HtmlControls.HtmlGenericControl AccessControlEntryControls;
        protected Rubicon.Web.UI.Controls.WebButton NewStateCombinationButton;
        protected Rubicon.Web.UI.Controls.WebButton NewAccessControlEntryButton;
        protected Rubicon.Web.UI.Controls.WebButton DeleteAccessControlListButton;
    }
}
