//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSample.UI {
    
    public partial class SearchResultPersonForm {
        protected Rubicon.Web.UI.Controls.HtmlHeadContents HtmlHeadContents;
        protected Rubicon.Data.DomainObjects.ObjectBinding.Web.SearchObjectDataSourceControl PersonSearchDataSource;
        protected Rubicon.Web.UI.Controls.FormGridManager FormGridManager;
        protected WebSample.UI.NavigationTabs NavigationTabs;
        protected System.Web.UI.HtmlControls.HtmlForm Form1;
        protected Rubicon.ObjectBinding.Web.UI.Controls.BocList PersonList;
    }
}
