//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBWTest.IndividualControlTests {
    
    public partial class BocLiteralUserControl {
        protected System.Web.UI.HtmlControls.HtmlGenericControl NonVisualControls;
        protected Rubicon.Web.UI.Controls.FormGridManager FormGridManager;
        protected Rubicon.ObjectBinding.Reflection.ReflectionBusinessObjectDataSourceControl CurrentObject;
        protected System.Web.UI.HtmlControls.HtmlTable FormGrid;
        protected Rubicon.ObjectBinding.Web.UI.Controls.BocTextValue FirstNameField;
        protected Rubicon.ObjectBinding.Web.UI.Controls.BocTextValue LastNameField;
        protected Rubicon.ObjectBinding.Web.UI.Controls.BocLiteral CVField;
        protected System.Web.UI.WebControls.Label CVFieldValueLabel;
        protected Rubicon.ObjectBinding.Web.UI.Controls.BocLiteral UnboundCVField;
        protected System.Web.UI.WebControls.Label UnboundCVFieldValueLabel;
        protected Rubicon.Web.UI.Controls.WebButton CVTestSetNullButton;
        protected Rubicon.Web.UI.Controls.WebButton CVTestSetNewValueButton;
    }
}
