//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBWTest.IndividualControlTests {
    
    
    /// <summary>
    /// IndividualControlTestForm class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class IndividualControlTestForm {

      protected Rubicon.Web.UI.Controls.WebButton SaveAndRestartButton;
      protected System.Web.UI.WebControls.PlaceHolder UserControlPlaceHolder;
      protected Rubicon.Web.UI.Controls.WebButton SaveButton;
      protected Rubicon.Web.UI.Controls.WebButton PostBackButton;
      protected System.Web.UI.WebControls.Literal Stack;
      protected System.Web.UI.UpdatePanel StackUpdatePanel;

      protected Rubicon.Web.UI.Controls.WebButton CancelButton;
      
        /// <summary>
        /// HtmlHeadContents control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Rubicon.Web.UI.Controls.HtmlHeadContents HtmlHeadContents;
        
        /// <summary>
        /// Form control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm Form;
        
        /// <summary>
        /// ScriptManager control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.ScriptManager ScriptManager;
        
        /// <summary>
        /// CurrentObject control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Rubicon.ObjectBinding.Web.UI.Controls.BindableObjectDataSourceControl CurrentObject;
    }
}
