//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rubicon.SecurityManager.Clients.Web.UI {
    
    public partial class CurrentClientControl {
        protected Rubicon.ObjectBinding.Web.UI.Controls.BocReferenceValue CurrentUserField;
        protected Rubicon.ObjectBinding.Web.UI.Controls.BocReferenceValue CurrentClientField;
    }
}
