//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rubicon.SecurityManager.Client.Web.UI.OrganizationalStructure {
    
    public partial class OrganizationalStructureMasterPage {
        protected System.Web.UI.HtmlControls.HtmlHead Head;
        protected System.Web.UI.HtmlControls.HtmlForm ThisForm;
        protected Rubicon.Kis.Client.Web.UI.AdministrationUI.SecurityManagerNavigationTabs SecurityManagerNavigationTabs;
        protected System.Web.UI.WebControls.ContentPlaceHolder TopControlsPlaceHolder;
        protected System.Web.UI.WebControls.Label ErrorsOnPageLabel;
        protected System.Web.UI.WebControls.ContentPlaceHolder MainContentPlaceHolder;
        protected System.Web.UI.WebControls.ContentPlaceHolder BottomControlsPlaceHolder;
    }
}
