//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rubicon.SecurityManager.Client.Web.OrganizationalStructure.UI {
    
    public partial class EditConcretePositionForm {
        protected System.Web.UI.WebControls.Label ErrorsOnPageLabel;
        protected Rubicon.SecurityManager.Client.Web.OrganizationalStructure.UI.EditConcretePositionControl EditConcretePositionControl;
        protected Rubicon.Web.UI.Controls.WebButton CloseButton;
        protected Rubicon.Web.UI.Controls.WebButton CancelButton;
    }
}
