//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rubicon.SecurityManager.Client.Web.OrganizationalStructure.UI {
    
    public partial class EditUserControl {
        protected Rubicon.Web.UI.Controls.FormGridManager FormGridManager;
        protected Rubicon.Data.DomainObjects.ObjectBinding.Web.DomainObjectDataSourceControl CurrentObject;
        protected System.Web.UI.HtmlControls.HtmlTable FormGrid;
        protected Rubicon.Web.UI.Controls.SmartLabel UserLabel;
        protected Rubicon.ObjectBinding.Web.UI.Controls.BocTextValue UserNameField;
        protected Rubicon.ObjectBinding.Web.UI.Controls.BocTextValue TitleField;
        protected Rubicon.ObjectBinding.Web.UI.Controls.BocTextValue FirstnameField;
        protected Rubicon.ObjectBinding.Web.UI.Controls.BocTextValue LastNameField;
        protected Rubicon.ObjectBinding.Web.UI.Controls.BocReferenceValue GroupField;
    }
}
