//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rubicon.SecurityManager.Clients.Web.UI.OrganizationalStructure {
    
    public partial class EditRoleForm {
        protected Rubicon.SecurityManager.Clients.Web.UI.ErrorMessageControl ErrorMessageControl;
        protected Rubicon.SecurityManager.Clients.Web.UI.OrganizationalStructure.EditRoleControl EditRoleControl;
        protected Rubicon.Web.UI.Controls.WebButton CloseButton;
        protected Rubicon.Web.UI.Controls.WebButton CancelButton;
    }
}
